string id_navigate_to # Waypoint id string for where to go
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages
---
string waypoint_id

