# Capture an image from the camera

# Select which screen should be captured
string screen

# Directory to which the image(s) should be saved
string save_dir

# Base filename for the image capture. This will be suffixed with the screen used for the capture, as well as the date #
# and time of the capture. It will look something like filename_screen_%Y-%m-%d-%H-%M-%S.jpg. If not provided, the
# default filename is spot_cam_capture
string filename

# Duration for which the images should be captured. Each image received on the stream will be saved to a separate file
# This takes precedence over capture_count
int32 capture_duration

# Specify the number of images which should be captured from the image stream. Not used if capture_duration is nonzero
int32 capture_count
-----
bool success
string message