#!/usr/bin/env python3

from interactive_markers.interactive_marker_server import *
from interactive_markers.menu_handler import *
from visualization_msgs.msg import *

import rospy

from interactive_marker_utils import (GoToMarkerCallback, 
                                    GrabMarkerCallback, 
                                    DragToMarkerCallback,
                                    create_interactive_marker,
                                    MarkerPoseSubscriber)


import numpy as np
        
def main():
    rospy.init_node("spot_interactive_marker", anonymous=True)
    mesh_dir = "package://spot_viz/meshes"
    chair_arm = {
        'name': 'chair_arm',
        'mesh': f'{mesh_dir}/chair_arm.stl',
        'mesh_scale': 0.001,
        'grasp_t': [0.0, 0.0, 0.0],
        'grasp_R': [0, 0, np.pi/2],
        'tag_pose_offset': np.eye(4),
    }
    chair = {
        'name': 'chair',
        'mesh': f"{mesh_dir}/office_chair/10239_Office_Chair_v1_L3.obj",
        'mesh_scale': 0.0075,
        'grasp_t': [0.2, 0.0, 0.5],
        'grasp_R': [0, 0, np.pi],
        'tag_pose_offset': np.array([[1.0,  0.0, 0.0, 0.0],
                                     [0.0,  0.0, -1.0, 0.3],
                                     [0.0, 1.0, 0.0, 0.1],]),
    }
    obj = chair

    # spawn cube with interactive marker in rviz for right arm
    server = InteractiveMarkerServer("chair_handle")
    int_marker = create_interactive_marker(
            name=obj['name'],
            mesh=obj['mesh'],
            mesh_scale=obj['mesh_scale'],
            control_axis=['x','y','z', 'roll', 'pitch', 'yaw']
            )
    server.insert(int_marker, lambda feedback: feedback)
    server.applyChanges()

    # Add a menu
    menu_handler = MenuHandler()
    
    t, R = obj['grasp_t'], obj['grasp_R']
    menu_handler.insert("go to", callback=GoToMarkerCallback())
    menu_handler.insert("grasp left handle", callback=GrabMarkerCallback(t=t, R=R))
    menu_handler.insert("drag to", callback=DragToMarkerCallback(t=t, R=R))
    menu_handler.apply(server, int_marker.name)

    update_merker_sub = MarkerPoseSubscriber(
                                'tcpu', 
                                int_marker, 
                                server, 
                                T=obj['tag_pose_offset']
                            )

    rospy.spin()

if __name__ == "__main__":
    main()