name: Docker image upload

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract branch name
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT && \
          echo "CORRECTED_BRANCH_NAME=$(echo ${new_name_for_docker/\//-}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Print branch name
        run: |
          echo ${{ steps.extract_branch.outputs.BRANCH_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spot_ros:${{ steps.extract_branch.outputs.CORRECTED_BRANCH_NAME }}
          secrets: |
            "SPOTROS_GIT_BRANCH=${{ steps.extract_branch.outputs.BRANCH_NAME }}"
