name: Docker image upload

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Print branch name
        run: |
          echo ${{ github.ref_name }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spot_ros:${${{ github.ref_name }}/\//-}
          secrets: |
            "SPOTROS_GIT_BRANCH=${${{ github.ref_name }}/\//-}"
