name: Run spot_driver unit tests on rostest and rosunit

# We only want these changes to run when we push to the main branch
on: [push]

# Environmental variables
env:
  SPOT_ARM: 1

jobs:
  spot_driver-unit-tests:
    # All steps inside this job will run inside the ROS Noetic container
    container: public.ecr.aws/docker/library/ros:noetic
    runs-on: ubuntu-latest
    # Let's ensure we use bash, and work within our catkin worksapce
    defaults:
      run:
        shell: bash
    steps:
      # Create directory to check out the code to
      - name: Create catkin_ws directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/catkin_ws/src

      # Check out the code
      - uses: actions/checkout@v2
        with:
          path: catkin_ws/src/spot_ros

      - name: Check that code has been downloaded correctly
        run: |
          ls $GITHUB_WORKSPACE/catkin_ws/src
          ls $GITHUB_WORKSPACE/catkin_ws/src/spot_ros

      # Install the Turtlebot and Gazebo packages
      - name: Install dependencies (minus qttools)
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            python3-pip \
            ros-noetic-tf2-bullet
          pip install cython \
            bosdyn-client \
            bosdyn-mission \
            bosdyn-api \
            bosdyn-core \
            empy
        working-directory: catkin_ws/

      # Build our workspace
      - name: Build workspace for spot_driver
        run: |
          source /opt/ros/noetic/setup.bash
          rosdep update
          rosdep install --from-paths src --ignore-src -y
          ls $GITHUB_WORKSPACE/catkin_ws
          catkin_make --only-pkg-with-deps spot_driver
        working-directory: catkin_ws/

      # Run our ROS test!
      - name: Run tests
        run: |
          source devel/setup.bash &&
          rostest spot_driver run_tests.test --text
        working-directory: catkin_ws/
